CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  op_id TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS notes_op_id_idx ON notes(op_id); 